"set coloscheme
colo evening

"set case not sensetive
set ignorecase

"set line number
set nu

"cursorline
set cursorline

" Super tab
let g:superTabRetainCompletionType=2
let g:SuperTabDefaultCompletionType="<C-X><C-P>"
" 设置按下<Tab>后默认的补全方式, 默认是<C-P>
" 现在改为<C-X><C-O>. 关于<C-P>的补全方式 
" 还有其他的补全方式, 你可以看看下面的一些帮助:
" :help ins-completion
" :help compl-omni

let g:superTabRetainCompletionType=2
" 0 - 不记录上次的补全方式
" 1 - 记住上次的补全方式,直到用其他的补全命令改变它
" 2 - 记住上次的补全方式,直到按ESC退出插入模式为止

" Taglist
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1

" Winmanager
let g:winManagerWindowLayout='FileExplorer|TagList'
nmap wm :WMToggle<cr>

" statusline
"set statusline=%2*%n%m%r%h%w%*\ %F\ %1*[FORMAT=%2*%{&ff}:%{&fenc!=''?&fenc:&enc}%1*]\ [TYPE=%2*%Y%1*]\ [COL=%2*%03v%1*]\ [ROW=%2*%03l%1*/%3*%L(%p%%)%1*]\

" statusline
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
set laststatus=2

" search option
set hlsearch

" set indentation
set tabstop=4
set softtabstop=4
set expandtab  " replace tab with spaces
set shiftwidth=4
set autoindent
set cindent
if &term=="xterm"
	set t_Co=8
	set t_Sb=^[[4%dm
	set t_Sf=^[[3%dm
endif

" set filetype auto detect function
let Tlist_Show_One_File=0   "显示多个文件的tags
let Tlist_File_Fold_Auto_Close=1 "非当前文件，函数列表折叠隐藏
let Tlist_Exit_OnlyWindow=1 "在taglist是最后一个窗口时退出vim
let Tlist_Use_SingleClick=1 "单击时跳转
let Tlist_GainFocus_On_ToggleOpen=1 "打开taglist时获得输入焦点
let Tlist_Process_File_Always=1 "不管taglist窗口是否打开，始终解析文件中的tag


" show the tab 
set list
set listchars=tab:>.,trail:.,extends:#,

" enable mouse
set mouse=a

