#!/bin/bash

function isValueInArr(){
	params=(DPST dpst VPP vpp WIFI wifi)
	value=$1
	array=${params[@]}
	for i in ${array[@]}
	do
#		echo "i = $i value = $value"
		if [ $i == $value ]; then
			echo $i
			return
		fi
	done
	echo "False"
}
## METHOD 1
#echo $@
#array_len=${#@}
#echo "array_len=$array_len"
#arr=${@:2:$array_len-1}
#echo ${arr[@]}

## METHOD 2
arr=($@)
echo ${arr[@]}
unset arr[0]
echo ${arr[@]}

for i in ${arr[@]}
do
	if [ $(isValueInArr $i) == 'False' ]; then
		echo "NOT FOUND IN ARRAY"
	else
		if [ $i == 'DPST' ] || [ $i == 'dpst' ];
		then
			echo  "DPST ENABLE"
		elif [ $i == 'VPP' ] || [ $i == 'vpp' ];
		then
			echo  "VPP ENABLE"
		elif [ $i == 'WIFI' ] || [ $i == 'wifi' ];
		then
			echo "WIFI ENABLE"
		fi
	fi
done

#res=$(isValueInArr dpst)
#echo "res = $res"
